# Generated by Django 3.0 on 2019-12-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_auto_20191218_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='desccription',
            new_name='description',
        ),
    ]
