# Generated by Django 3.0 on 2019-12-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0006_auto_20191218_1621'),
        ('jedzonko', '0002_recipe_preparation'),
    ]

    operations = [
    ]
