# Generated by Django 3.0 on 2019-12-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0007_merge_20191218_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayname',
            name='name',
            field=models.IntegerField(choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek'), (6, 'Sobota'), (7, 'Niedziela')]),
        ),
        migrations.AlterField(
            model_name='recipeplan',
            name='day_name',
            field=models.IntegerField(choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek'), (6, 'Sobota'), (7, 'Niedziela')]),
        ),
    ]
