# Generated by Django 3.0 on 2019-12-20 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0010_auto_20191220_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='day_names',
            field=models.ManyToManyField(through='jedzonko.RecipePlan', to='jedzonko.DayName'),
        ),
        migrations.AlterField(
            model_name='recipeplan',
            name='day_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_in_matrix', to='jedzonko.DayName'),
        ),
        migrations.AlterField(
            model_name='recipeplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_in_matrix', to='jedzonko.Plan'),
        ),
        migrations.AlterField(
            model_name='recipeplan',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_in_matrix', to='jedzonko.Recipe'),
        ),
    ]
