# Generated by Django 3.0 on 2019-12-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0013_auto_20191220_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayname',
            name='day_name',
            field=models.CharField(choices=[('pon', 'Poniedziałek'), ('wt', 'Wtorek'), ('śr', 'Środa'), ('czw', 'Czwartek'), ('pt', 'Piątek'), ('sob', 'Sobota'), ('nd', 'Niedziela')], max_length=16),
        ),
    ]
